package db

import (
	"errors"
	"sync"
	"time"
)

// Node represents a monitored system instance.
type Node struct {
	NodeID    string            `json:"node_id"`
	Name      string            `json:"name"`
	IP        string            `json:"ip,omitempty"`
	OS        string            `json:"os"`
	Platform  string            `json:"platform"`
	CPUCount  int               `json:"cpu_count"`
	Services  map[string]string `json:"services"`  // service name -> status
	LastSeen  time.Time         `json:"last_seen"`
}

// Incident represents a telemetry alert generated by an agent error.
type Incident struct {
	ID              string    `json:"id"`
	Title           string    `json:"title"`
	NodeID          string    `json:"node_id"`
	LogLine         string    `json:"log_line"`
	Service         string    `json:"service"`
	Diagnosis       string    `json:"diagnosis"`
	DiagnosisSource string    `json:"diagnosis_source"` // "ai", "heuristic", "reanalyzed"
	Remediation     []string  `json:"remediation"`      // step-by-step instructions
	Status          string    `json:"status"`           // "critical", "acknowledged", "resolved", "annulled"
	AssignedTeam    string    `json:"assigned_team"`
	Timestamp       time.Time `json:"timestamp"`
}

// UptimeRecord stores hourly uptime snapshots for nodes.
type UptimeRecord struct {
	Timestamp  time.Time         `json:"timestamp"`
	NodeStatus map[string]bool   `json:"node_status"` // node_id -> online?
	OnlineCount int              `json:"online_count"`
	TotalCount  int              `json:"total_count"`
}

// Store defines the interface for database operations.
type Store interface {
	RegisterNode(node Node) error
	ListNodes() ([]Node, error)
	GetNode(nodeID string) (*Node, error)
	DeleteNode(nodeID string) error
	UpdateNodeLastSeen(nodeID string) error
	AddIncident(inc Incident) (Incident, error)
	ListIncidents() ([]Incident, error)
	UpdateIncident(id string, status string) (Incident, error)
	UpdateIncidentTeam(id string, team string) (Incident, error)
	UpdateIncidentDiagnosis(id, title, diagnosis, source string, remediation []string) (Incident, error)
	RecordUptime(record UptimeRecord) error
	GetUptimeHistory(hours int) ([]UptimeRecord, error)
	ClearAll() error
}

// MemoryStore is an in-memory, thread-safe implementation of Store.
type MemoryStore struct {
	mu        sync.RWMutex
	nodes     map[string]Node
	incidents []Incident
	uptime    []UptimeRecord
}

// NewMemoryStore initializes a MemoryStore instance.
func NewMemoryStore() *MemoryStore {
	return &MemoryStore{
		nodes:     make(map[string]Node),
		incidents: make([]Incident, 0),
		uptime:    make([]UptimeRecord, 0),
	}
}

// RegisterNode saves or updates a node in the database.
func (ms *MemoryStore) RegisterNode(node Node) error {
	ms.mu.Lock()
	defer ms.mu.Unlock()

	node.LastSeen = time.Now()
	// Default name to NodeID if empty
	if node.Name == "" {
		node.Name = node.NodeID
	}
	ms.nodes[node.NodeID] = node
	return nil
}

// ListNodes returns all registered nodes.
func (ms *MemoryStore) ListNodes() ([]Node, error) {
	ms.mu.RLock()
	defer ms.mu.RUnlock()

	list := make([]Node, 0, len(ms.nodes))
	for _, n := range ms.nodes {
		list = append(list, n)
	}
	return list, nil
}

// GetNode returns a single node by ID.
func (ms *MemoryStore) GetNode(nodeID string) (*Node, error) {
	ms.mu.RLock()
	defer ms.mu.RUnlock()

	if n, ok := ms.nodes[nodeID]; ok {
		return &n, nil
	}
	return nil, errors.New("node not found")
}

// DeleteNode removes a node by ID.
func (ms *MemoryStore) DeleteNode(nodeID string) error {
	ms.mu.Lock()
	defer ms.mu.Unlock()

	delete(ms.nodes, nodeID)
	return nil
}

// UpdateNodeLastSeen updates the last_seen timestamp for a node.
func (ms *MemoryStore) UpdateNodeLastSeen(nodeID string) error {
	ms.mu.Lock()
	defer ms.mu.Unlock()

	if n, ok := ms.nodes[nodeID]; ok {
		n.LastSeen = time.Now()
		ms.nodes[nodeID] = n
		return nil
	}
	return errors.New("node not found")
}

// AddIncident appends a new incident to the list.
func (ms *MemoryStore) AddIncident(inc Incident) (Incident, error) {
	ms.mu.Lock()
	defer ms.mu.Unlock()

	if inc.ID == "" {
		return inc, errors.New("incident ID cannot be empty")
	}
	inc.Timestamp = time.Now()
	ms.incidents = append([]Incident{inc}, ms.incidents...) // Prepend so newest is first
	return inc, nil
}

// ListIncidents returns all incidents in reverse chronological order.
func (ms *MemoryStore) ListIncidents() ([]Incident, error) {
	ms.mu.RLock()
	defer ms.mu.RUnlock()

	return ms.incidents, nil
}

// ClearAll resets all data.
func (ms *MemoryStore) ClearAll() error {
	ms.mu.Lock()
	defer ms.mu.Unlock()

	ms.nodes = make(map[string]Node)
	ms.incidents = make([]Incident, 0)
	return nil
}

// UpdateIncident changes the status of an existing incident.
func (ms *MemoryStore) UpdateIncident(id string, status string) (Incident, error) {
	ms.mu.Lock()
	defer ms.mu.Unlock()

	for i, inc := range ms.incidents {
		if inc.ID == id {
			ms.incidents[i].Status = status
			return ms.incidents[i], nil
		}
	}
	return Incident{}, errors.New("incident not found")
}

// UpdateIncidentTeam assigns an incident to a team.
func (ms *MemoryStore) UpdateIncidentTeam(id string, team string) (Incident, error) {
	ms.mu.Lock()
	defer ms.mu.Unlock()

	for i, inc := range ms.incidents {
		if inc.ID == id {
			ms.incidents[i].AssignedTeam = team
			if ms.incidents[i].Status == "critical" {
				ms.incidents[i].Status = "acknowledged"
			}
			return ms.incidents[i], nil
		}
	}
	return Incident{}, errors.New("incident not found")
}

// UpdateIncidentDiagnosis re-runs AI analysis on an incident.
func (ms *MemoryStore) UpdateIncidentDiagnosis(id, title, diagnosis, source string, remediation []string) (Incident, error) {
	ms.mu.Lock()
	defer ms.mu.Unlock()

	for i, inc := range ms.incidents {
		if inc.ID == id {
			ms.incidents[i].Title = title
			ms.incidents[i].Diagnosis = diagnosis
			ms.incidents[i].DiagnosisSource = source
			ms.incidents[i].Remediation = remediation
			return ms.incidents[i], nil
		}
	}
	return Incident{}, errors.New("incident not found")
}

// RecordUptime saves an hourly uptime snapshot.
func (ms *MemoryStore) RecordUptime(record UptimeRecord) error {
	ms.mu.Lock()
	defer ms.mu.Unlock()

	ms.uptime = append(ms.uptime, record)

	// Keep only last 7 days of records (168 hours)
	if len(ms.uptime) > 168 {
		ms.uptime = ms.uptime[len(ms.uptime)-168:]
	}
	return nil
}

// GetUptimeHistory returns uptime records for the last N hours.
func (ms *MemoryStore) GetUptimeHistory(hours int) ([]UptimeRecord, error) {
	ms.mu.RLock()
	defer ms.mu.RUnlock()

	if hours <= 0 || hours > len(ms.uptime) {
		hours = len(ms.uptime)
	}
	start := len(ms.uptime) - hours
	result := make([]UptimeRecord, hours)
	copy(result, ms.uptime[start:])
	return result, nil
}