package db

import (
	"errors"
	"sync"
	"time"
)

// Node represents a monitored system instance.
type Node struct {
	NodeID    string            `json:"node_id"`
	Name      string            `json:"name"`
	OS        string            `json:"os"`
	Platform  string            `json:"platform"`
	CPUCount  int               `json:"cpu_count"`
	Services  map[string]string `json:"services"`  // service name -> status
	LastSeen  time.Time         `json:"last_seen"`
}

// Incident represents a telemetry alert generated by an agent error.
type Incident struct {
	ID          string    `json:"id"`
	NodeID      string    `json:"node_id"`
	LogLine     string    `json:"log_line"`
	Service     string    `json:"service"`
	Diagnosis   string    `json:"diagnosis"`
	Remediation []string  `json:"remediation"` // step-by-step instructions
	Status      string    `json:"status"`      // "critical", "resolved"
	Timestamp   time.Time `json:"timestamp"`
}

// Store defines the interface for database operations.
type Store interface {
	RegisterNode(node Node) error
	ListNodes() ([]Node, error)
	AddIncident(inc Incident) (Incident, error)
	ListIncidents() ([]Incident, error)
	ClearAll() error
}

// MemoryStore is an in-memory, thread-safe implementation of Store.
type MemoryStore struct {
	mu        sync.RWMutex
	nodes     map[string]Node
	incidents []Incident
}

// NewMemoryStore initializes a MemoryStore instance.
func NewMemoryStore() *MemoryStore {
	return &MemoryStore{
		nodes:     make(map[string]Node),
		incidents: make([]Incident, 0),
	}
}

// RegisterNode saves or updates a node in the database.
func (ms *MemoryStore) RegisterNode(node Node) error {
	ms.mu.Lock()
	defer ms.mu.Unlock()

	node.LastSeen = time.Now()
	// Default name to NodeID if empty
	if node.Name == "" {
		node.Name = node.NodeID
	}
	ms.nodes[node.NodeID] = node
	return nil
}

// ListNodes returns all registered nodes.
func (ms *MemoryStore) ListNodes() ([]Node, error) {
	ms.mu.RLock()
	defer ms.mu.RUnlock()

	list := make([]Node, 0, len(ms.nodes))
	for _, n := range ms.nodes {
		list = append(list, n)
	}
	return list, nil
}

// AddIncident appends a new incident to the list.
func (ms *MemoryStore) AddIncident(inc Incident) (Incident, error) {
	ms.mu.Lock()
	defer ms.mu.Unlock()

	if inc.ID == "" {
		return inc, errors.New("incident ID cannot be empty")
	}
	inc.Timestamp = time.Now()
	ms.incidents = append([]Incident{inc}, ms.incidents...) // Prepend so newest is first
	return inc, nil
}

// ListIncidents returns all incidents in reverse chronological order.
func (ms *MemoryStore) ListIncidents() ([]Incident, error) {
	ms.mu.RLock()
	defer ms.mu.RUnlock()

	return ms.incidents, nil
}

// ClearAll resets all data.
func (ms *MemoryStore) ClearAll() error {
	ms.mu.Lock()
	defer ms.mu.Unlock()

	ms.nodes = make(map[string]Node)
	ms.incidents = make([]Incident, 0)
	return nil
}